version: '3'
services:
  
  meu-mongodb:
    build:
      context: .
      dockerfile: mongodb.dockerfile
    container_name: meu-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    networks:
      - rede-app

  mongo-express:
    build:
      context: .
      dockerfile: mongo-express.dockerfile
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - rede-app
    depends_on:
      - meu-mongodb

  node1:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: node1
    ports:
      - 3001:3000
    networks:
      - rede-app
    depends_on:
      - meu-mongodb
        
  node2:
    build:
        context: .
        dockerfile: app.dockerfile
    container_name: node2
    ports:
      - 3002:3000
    networks:
      - rede-app
    depends_on:
      - meu-mongodb

  node3:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: node3
    ports:
      - 3003:3000
    networks:
      - rede-app
    depends_on:
      - meu-mongodb

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - 80:80
    networks:
      - rede-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node1
      - node2
      - node3

volumes:
  mongo-volume:

networks:
  rede-app:
    driver: bridge